#logLevel: ERROR

#InsecureSkipVerify: true

defaultEntryPoints:
  - https
  - http

api:
  dashboard: true
  insecure: true

traefikLog:
  filepath: "/var/log/traefik.log"

accessLog:
  filepath: "/var/log/access.log"

entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'
    http:
      tls: {}

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
  file:
    directory: /etc/traefik
